/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.25).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.dpdm.gateway_api.api;

import com.dpdm.gateway_api.model.FileResponse;
import com.dpdm.gateway_api.model.Institution;
import org.springframework.core.io.Resource;
import com.dpdm.gateway_api.model.SignRequest;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2021-05-27T01:37:43.340Z[GMT]")
@Validated
public interface InstitutionApi {

    @Operation(summary = "create an institution", description = "operationId: createInstitution", security = {
        @SecurityRequirement(name = "bearerAuth")    }, tags={ "Institution" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "OK") })
    @RequestMapping(value = "/institutions",
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<Void> createInstitution(@Parameter(in = ParameterIn.DEFAULT, description = "the institution details", required=true, schema=@Schema()) @Valid @RequestBody Institution body);


    @Operation(summary = "delete a request", description = "operationId: deleteRequest", security = {
        @SecurityRequirement(name = "bearerAuth")    }, tags={ "Institution" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "OK") })
    @RequestMapping(value = "/institution/{id}/requests/{reqid}",
        method = RequestMethod.DELETE)
    ResponseEntity<Void> deleteRequest(@Parameter(in = ParameterIn.PATH, description = "id string that was sent with the file", required=true, schema=@Schema()) @PathVariable("id") String id, @Parameter(in = ParameterIn.PATH, description = "id string that was sent with the file", required=true, schema=@Schema()) @PathVariable("reqid") String reqid);


    @Operation(summary = "Get file link", description = "operationId: getDownloadLink", security = {
        @SecurityRequirement(name = "bearerAuth")    }, tags={ "Institution" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "OK") })
    @RequestMapping(value = "/institution/{id}/templates/{fileid}",
        method = RequestMethod.DELETE)
    ResponseEntity<Void> deleteTemplate(@Parameter(in = ParameterIn.PATH, description = "id string that was sent with the file", required=true, schema=@Schema()) @PathVariable("id") String id, @Parameter(in = ParameterIn.PATH, description = "id string that was sent with the file", required=true, schema=@Schema()) @PathVariable("fileid") String fileid);


    @Operation(summary = "get lsit of institutions", description = "operationId: getInstitutions", tags={ "Institution" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "OK", content = @Content(schema = @Schema(implementation = Institution.class))) })
    @RequestMapping(value = "/institution/{id}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Institution> getInstitution(@Parameter(in = ParameterIn.PATH, description = "", required=true, schema=@Schema()) @PathVariable("id") String id);


    @Operation(summary = "get lsit of files signed by the institution", description = "operationId: getInstitutionFiles", security = {
        @SecurityRequirement(name = "bearerAuth")    }, tags={ "Institution" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "OK", content = @Content(array = @ArraySchema(schema = @Schema(implementation = FileResponse.class)))) })
    @RequestMapping(value = "/institution/{id}/files",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<FileResponse>> getInstitutionFiles(@Parameter(in = ParameterIn.PATH, description = "institutions id", required=true, schema=@Schema()) @PathVariable("id") String id);


    @Operation(summary = "get lsit of templates", description = "getInstitutionTemplates", tags={ "Institution" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "OK", content = @Content(array = @ArraySchema(schema = @Schema(implementation = FileResponse.class)))) })
    @RequestMapping(value = "/institution/{id}/templates",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<FileResponse>> getInstitutionTemplates(@Parameter(in = ParameterIn.PATH, description = "institutions id", required=true, schema=@Schema()) @PathVariable("id") String id);


    @Operation(summary = "get lsit of institutions", description = "operationId: getInstitutions", tags={ "Institution" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "OK", content = @Content(array = @ArraySchema(schema = @Schema(implementation = Institution.class)))) })
    @RequestMapping(value = "/institutions",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Institution>> getInstitutions();


    @Operation(summary = "Get the companies requests", description = "operationId: getRequests", security = {
        @SecurityRequirement(name = "bearerAuth")    }, tags={ "Institution" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "OK", content = @Content(array = @ArraySchema(schema = @Schema(implementation = SignRequest.class)))) })
    @RequestMapping(value = "/institution/{id}/requests",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<SignRequest>> getRequests(@Parameter(in = ParameterIn.PATH, description = "id string that was sent with the file", required=true, schema=@Schema()) @PathVariable("id") String id);


    @Operation(summary = "Get file link", description = "operationId: getDownloadLink", security = {
        @SecurityRequirement(name = "bearerAuth")    }, tags={ "Institution" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "OK", content = @Content(schema = @Schema(implementation = String.class))) })
    @RequestMapping(value = "/institution/{id}/templates/{fileid}/dlink",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<String> getTemplateDownloadLink(@Parameter(in = ParameterIn.PATH, description = "id string that was sent with the file", required=true, schema=@Schema()) @PathVariable("id") String id, @Parameter(in = ParameterIn.PATH, description = "id string that was sent with the file", required=true, schema=@Schema()) @PathVariable("fileid") String fileid);


    @Operation(summary = "send a request", description = "operationId: sendRequest", security = {
        @SecurityRequirement(name = "bearerAuth")    }, tags={ "Institution" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "OK") })
    @RequestMapping(value = "/institution/{id}/requests",
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<Void> sendRequest(@Parameter(in = ParameterIn.PATH, description = "id string that was sent with the file", required=true, schema=@Schema()) @PathVariable("id") String id, @Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody SignRequest body);


    @Operation(summary = "upload template", description = "uploadInstitutionTemplate", security = {
        @SecurityRequirement(name = "bearerAuth")    }, tags={ "Institution" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "OK") })
    @RequestMapping(value = "/institution/{id}/templates",
        consumes = { "multipart/form-data" }, 
        method = RequestMethod.POST)
    ResponseEntity<Void> uploadInstitutionTemplate(@Parameter(in = ParameterIn.PATH, description = "institutions id", required=true, schema=@Schema()) @PathVariable("id") String id, @Parameter(description = "file detail") @Valid @RequestPart("file") MultipartFile filename);

}

